name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-firmwares:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build firmwares
      run: BUILD_IN_DOCKER=1 make
